"use client";

import { FileText, Calendar, User } from "lucide-react";

export default function ReportPreview() {
  return (
    <div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">

      <div className="mb-6 flex items-center gap-3">

        <div className="rounded-xl bg-indigo-100 p-3">
          <FileText className="text-indigo-600" size={24} />
        </div>

        <div>
          <h2 className="text-xl font-bold">
            Report Preview
          </h2>

          <p className="text-sm text-slate-500">
            Monthly Feedback Analytics
          </p>
        </div>

      </div>

      <div className="space-y-5">

        <div className="flex items-center gap-3">
          <Calendar className="text-slate-500" size={18} />
          <span>Generated: 20 July 2025</span>
        </div>

        <div className="flex items-center gap-3">
          <User className="text-slate-500" size={18} />
          <span>Generated By: Admin</span>
        </div>

        <div className="rounded-xl bg-slate-50 p-4">
          <p className="text-sm leading-7 text-slate-600">
            This report contains customer feedback insights,
            sentiment analysis, product ratings, review trends,
            category-wise performance and AI generated summary.
          </p>
        </div>

      </div>

    </div>
  );
}